[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]

[tool]
[tool.poetry]
authors = ["Amjad Masad <amjad.masad@gmail.com>"]
description = ""
name = "webproject"
version = "0.1.0"
[tool.poetry.dependencies]
python = "^3.7"
django = "^3.0"
[tool.poetry.dev-dependencies]
